name: avs_image
description: "A Flutter package that you can get and use images and SVG from
  local and network . Image - SVG Provider Supported"
topics:
  - image
  - network-image
  - svg-provider
  - avs-svg-provider
  - image-gallery
  
version: 1.1.5
homepage: https://github.com/ahmetveysels
repository: https://github.com/ahmetveysels/avsimage

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  avs_svg_provider: ^1.0.1
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
