name: avs_image
description: "Effortlessly display all images and SVG files. With zoom, ImageProvider support, and a built-in full-screen dialog feature!"
topics:
  - image
  - network-image
  - svg-provider
  - avs-svg-provider
  - image-gallery

version: 1.1.11
homepage: https://github.com/ahmetveysels
repository: https://github.com/ahmetveysels/avsimage

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  avs_svg_provider: ^1.0.1
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  http: ^1.2.2
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
